export const APP_CONFIG = {
  guideStyle: "nynex",
  guideBrand: "cable",
  previewContentMode: "video",
  previewInfoMode: "rotate",
  previewVideoMode: "channel",
  previewFixedChannel: null,
  previewVideoUrl: "",
  previewChannels: [401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
  previewCycleSeconds: 15,
  previewTransitions: [
    "blockDissolve",
    "wipeLeft",
    "wipeRight",
    "wipeUp",
    "wipeDown",
    "blindsHorizontal",
    "blindsVertical",
  ],
  previewTransitionMode: "random",
  previewTransitionSeconds: 1.2,
  previewMuted: false,
  mosaicChannels: [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
  mosaicCycleSeconds: 30,
  mosaicAudioUrl: "https://www.mp3streams.nl/zender/skyradio/stream/8-mp3-128",
  m3uUrl: "http://192.168.20.186:9191/output/m3u",
  xmltvUrl: "http://192.168.20.186:9191/output/epg",
  proxyPath: "/api/guide",
  refreshMinutes: 5,
  timeFormat: "12h",
  allowedGroups: ["UK - Documentaries", "UK - Entertainment", "UK - Movies", "UK - Sports"],
  stripNamePrefixes: true,
  channelLimit: 0,
  fallbackToDemoData: false,
  crtEffect: true,
  headerTagline: "Full listings on teletext",
  promos: [
    {
      title: "Unique To {brand} Customers",
      lines: ["USE YOUR REMOTE", "CONTROL AND YOU WILL"],
      highlight: "ONLY BE CHARGED",
      price: "£9.95",
      footer: "Details on Channel 51",
    },
    {
      title: "{brand} Pay Per View",
      lines: ["SATURDAY NIGHT", "BIG FIGHT LIVE"],
      highlight: "EXCLUSIVE TO CABLE",
      price: "£14.95",
      footer: "Order on Channel 51",
    },
    {
      title: "{brand} Local Channels",
      lines: ["YOUR LOCAL NEWS", "AND INFORMATION"],
      highlight: "ONLY ON CABLE",
      price: "",
      footer: "Channel 52",
    },
    {
      title: "Free Installation",
      lines: ["TELL YOUR", "FRIENDS ABOUT", "{brand} CABLE"],
      highlight: "AND RECEIVE",
      price: "1 MONTH",
      price2: "FREE",
      footer: "Call 0800 000 CABLE",
    },
  ],
};
